// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eejiyjdmpyejkznyiphw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlaml5amRtcHllamt6bnlpcGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNjIyNjksImV4cCI6MjA2NjgzODI2OX0.0rs60Q1Vag7jaCRvLwZ1Vdf2yGtOY-3uux7-kcvYJ7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});